name: super_star
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  provider: ^6.1.4
  wakelock_plus: ^1.2.11
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.1
  add_to_cart_animation: ^2.0.4
  just_audio: ^0.9.46
  pdf: ^3.11.3
  printing:
  flutter_thermal_printer: ^1.2.0
  permission_handler: ^11.4.0
  path_provider:
#  blue_thermal_printer:
  print_bluetooth_thermal: ^1.1.6
#  flutter_esc_pos_utils: ^1.0.1
  intl:
#  audioplayers: ^6.4.0
  barcode: ^2.2.9
  barcode_widget:
  window_manager: ^0.4.3
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.5
  thermal_printer: ^1.0.5
  esc_pos_utils_plus:
  pdf_render:
  image: ^4.5.4
  device_info_plus: ^11.4.0
#  barcode_image: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/card/
    - assets/spin/
    - assets/andar_b/
    - assets/jackpot/
    - assets/lucky_12/
    - assets/lucky_16/
    - assets/timer_36/
    - assets/triple_chance/
    - assets/sound/
    - assets/sound/sec_wheel_sound.mp3
    - assets/sound/sound_wheel.mp3
    - assets/sound/roulette_wheel.mp3
    - assets/sound/musicOne.mp3
    - assets/card_icons/
    - assets/dus_ka_dum/

